# github action to destroy ad hoc base
name: ad hoc | base | destroy [CDK]

on:
  workflow_dispatch:
    inputs:
      ad_hoc_base_name:
        description: 'Name for ad hoc base environment to destroy using CDK'
        required: true
        default: 'dev'
        type: string

jobs:
  destroy_ad_hoc_base:
    name: "Destroy ad hoc base infrastructure using CDK [${{ github.event.inputs.ad_hoc_base_name }}]"
    environment: ad-hoc-base-${{ github.event.inputs.ad_hoc_base_name }}
    env:
      AD_HOC_BASE_NAME: ${{ github.event.inputs.ad_hoc_base_name }}
      ACM_CERTIFICATE_ARN: ${{ secrets.ACM_CERTIFICATE_ARN }}
      DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install CDK
        run: |
          cd iac/cdk/ && npm install && npm i -g aws-cdk

      - name: "cdk destroy"
        id: cdk_destroy
        run: |
          cd iac/cdk/ && cdk destroy AdHocBaseStack --require-approval never
