# github action to create or update prod app env
name: prod | app | create / update [Terraform]

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Terraform workspace for prod app env'
        required: true
        default: 'stage'
        type: string

      prod_base_env:
        description: 'Prod base env'
        required: true
        default: 'stage'
        type: string

defaults:
  run:
    working-directory: iac/terraform/live/prod/app

jobs:
  prod_app_init_plan:
    name: "Terraform init and plan for prod app env [${{ github.event.inputs.workspace }}]"
    environment: prod
    runs-on: ubuntu-latest

    steps:

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.6
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: actions/checkout@v3

      - name: "terraform init and plan for prod app env"
        id: terraform_init_plan_prod_app
        env:

          # backend config
          TF_BACKEND_BUCKET: ${{ secrets.TF_BACKEND_BUCKET }}
          TF_BACKEND_REGION: ${{ secrets.TF_BACKEND_REGION }}
          TF_BACKEND_DYNAMODB_TABLE: ${{ secrets.TF_BACKEND_DYNAMODB_TABLE }}

          WORKSPACE: ${{ github.event.inputs.workspace }}

          # for terraform_remote_state
          TF_VAR_prod_base_env: ${{ github.event.inputs.prod_base_env }}
          TF_VAR_s3_bucket: ${{ secrets.TF_BACKEND_BUCKET }}

        run: |

          terraform -chdir=iac/terraform/live/prod/app \
            init \
            -backend-config="bucket=${TF_BACKEND_BUCKET}" \
            -backend-config="dynamodb_table=${TF_BACKEND_DYNAMODB_TABLE}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=${TF_BACKEND_REGION}" \
            -backend-config="workspace_key_prefix=prod/app"

          export VAR_FILE=envs/${WORKSPACE}.tfvars

          # create the workspace if it doesn't exist already
          terraform workspace new ${WORKSPACE} || echo "Workspace ${WORKSPACE} already exists or cannot be created"

          # set the TF_WORKSPACE environment variable
          export TF_WORKSPACE=$WORKSPACE

          terraform \
            plan \
            -no-color \
            -out=tfplan \
            -var-file=$VAR_FILE

      # https://github.com/actions/upload-artifact/issues?q=is%3Aissue+is%3Aopen+working-directory
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: "iac/terraform/live/prod/app/"

  prod_app_apply:
    name: "Prod app apply"
    environment: prod
    runs-on: ubuntu-latest
    needs: prod_app_init_plan

    steps:

      - uses: actions/checkout@v3

      # https://github.com/actions/upload-artifact/issues?q=is%3Aissue+is%3Aopen+working-directory
      - uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: "iac/terraform/live/prod/app"

      - name: "terraform apply for prod app env"
        id: terraform_prod_app_apply
        env:

          WORKSPACE: ${{ github.event.inputs.workspace }}

          # for terraform_remote_state
          TF_VAR_prod_base_env: ${{ github.event.inputs.prod_base_env }}
          TF_VAR_s3_bucket: ${{ secrets.TF_BACKEND_BUCKET }}

        run: |

          # create the workspace if it doesn't exist already
          terraform workspace new ${WORKSPACE} || echo "Workspace ${WORKSPACE} already exists or cannot be created"

          # set the TF_WORKSPACE environment variable
          export TF_WORKSPACE=$WORKSPACE

          terraform apply -auto-approve "tfplan"

          terraform output -json > terraform_outputs.json

      # backend_update_command
      - name: "Run post-deployment backend_update_command"
        id: backend_update
        run: |

          # get the backend_update_command command from Terraform outputs and write to file
          cat terraform_outputs.json | jq -r '.backend_update_command.value' > backend_update_command.sh

          # view migrate command
          cat backend_update_command.sh

          # make the file executable
          sudo chmod +x backend_update_command.sh

          # run migrate command
          ./backend_update_command.sh
