# github action to create or update shared resources
name: prod | base | create / update [Terraform]

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Terraform workspace for prod base env'
        required: true
        default: 'stage'
        type: string

# https://github.com/actions/upload-artifact/issues?q=is%3Aissue+is%3Aopen+working-directory
env:
  WORKING_DIRECTORY: iac/terraform/live/prod/base

defaults:
  run:
    working-directory: iac/terraform/live/prod/base

jobs:
  prod_base_create_update:
    name: "Create or update prod base env [${{ github.event.inputs.workspace }}]"
    environment: prod
    runs-on: ubuntu-latest

    steps:

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.6
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: actions/checkout@v3

      - name: "terraform init, plan and apply for prod base env"
        id: terraform_init_plan_apply_prod_base
        env:
          TF_BACKEND_BUCKET: ${{ secrets.TF_BACKEND_BUCKET }}
          TF_BACKEND_REGION: ${{ secrets.TF_BACKEND_REGION }}
          TF_BACKEND_DYNAMODB_TABLE: ${{ secrets.TF_BACKEND_DYNAMODB_TABLE }}
          WORKSPACE: ${{ github.event.inputs.workspace }}

          # Terraform variables
          TF_VAR_certificate_arn: ${{ secrets.ACM_CERTIFICATE_ARN }}
          TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}

        run: |
          export VAR_FILE=envs/${WORKSPACE}.tfvars

          terraform \
            init \
            -backend-config="bucket=${TF_BACKEND_BUCKET}" \
            -backend-config="dynamodb_table=${TF_BACKEND_DYNAMODB_TABLE}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=${TF_BACKEND_REGION}" \
            -backend-config="workspace_key_prefix=prod/base"

          # create the workspace if it doesn't exist already
          terraform workspace new ${WORKSPACE} || echo "Workspace ${WORKSPACE} already exists or cannot be created"

          # set the TF_WORKSPACE environment variable
          export TF_WORKSPACE=$WORKSPACE

          terraform \
            plan \
            -no-color \
            -out=tfplan \
            -var-file=$VAR_FILE

      # https://github.com/actions/upload-artifact/issues?q=is%3Aissue+is%3Aopen+working-directory
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: "iac/terraform/live/prod/base/"

  # https://developer.hashicorp.com/terraform/tutorials/automation/automate-terraform#plan-and-apply-on-different-machines
  prod_base_deploy:
    name: "Prod base deploy"
    environment: prod
    runs-on: ubuntu-latest
    needs: prod_base_create_update

    steps:

      - uses: actions/checkout@v2

      # https://github.com/actions/upload-artifact/issues?q=is%3Aissue+is%3Aopen+working-directory
      - uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: "iac/terraform/live/prod/base"

      - name: ls
        run: |
          ls -al

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.6
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: terraform apply
        id: terraform_apply
        env:
          WORKSPACE: ${{ github.event.inputs.workspace }}
        run: |

          # https://github.com/hashicorp/terraform/issues/24010#issuecomment-592936990
          chmod -R a+x ./.terraform/*

          # create the workspace if it doesn't exist already
          terraform workspace new ${WORKSPACE} || echo "Workspace ${WORKSPACE} already exists or cannot be created"

          # set the TF_WORKSPACE environment variable
          export TF_WORKSPACE=$WORKSPACE

          terraform apply -auto-approve "tfplan"
